FROM openjdk

COPY . /usr/src/app/KafkaDemoProducer

WORKDIR /usr/src/app/KafkaDemoProducer

ENTRYPOINT ["java", "-jar", "/usr/src/app/KafkaDemoProducer/out/artifacts/KafkaDemoProducer_jar/KafkaDemoProducer.jar"]